"""Pure domain types.  No I/O, no imports beyond pydantic and the standard library."""

from lumberjack.domain.accord import (
    Accord,
    Adopt,
    Channel,
    ChannelState,
    Defer,
    Directive,
    EscalateToForeman,
    Extract,
    NegotiationLimits,
    NegotiationMove,
    Resolution,
    Ruling,
    Split,
)
from lumberjack.domain.claim import (
    AccessMode,
    Claim,
    DenialReason,
    Lease,
    LeaseDecision,
    LeaseDenied,
    LeaseGranted,
    LeaseQueued,
    PathScope,
    Scope,
    SymbolScope,
    modes_conflict,
    scopes_overlap,
)
from lumberjack.domain.conflict import (
    ConflictedFile,
    ConflictReport,
    ConflictSource,
    Severity,
)
from lumberjack.domain.contract import AmendmentProposal, Contract, ContractBreach
from lumberjack.domain.events import Envelope, EventPayload, event_kinds
from lumberjack.domain.gate import CheckOutcome, CheckResult, GateReport
from lumberjack.domain.message import BROADCAST, Message
from lumberjack.domain.note import Note, Topic
from lumberjack.domain.symbols import ModuleNode, RepoMap, SymbolRef, signature_digest
from lumberjack.domain.task import (
    Abandoned,
    Assigned,
    AwaitingIntegration,
    Blocked,
    BlockReason,
    Landed,
    Pending,
    Running,
    Task,
    TaskGraph,
    TaskSpec,
)
from lumberjack.domain.vcs import (
    ChangeKind,
    FileChange,
    MergeOutcome,
    MergeTreeResult,
    RebaseOutcome,
    WorkingStatus,
)
from lumberjack.domain.workstream import (
    ArbitrationMode,
    Budget,
    DriftStatus,
    Snapshot,
    StandConfig,
    Workstream,
    Worktree,
)

__all__ = [
    "BROADCAST",
    "Abandoned",
    "AccessMode",
    "Accord",
    "Adopt",
    "AmendmentProposal",
    "ArbitrationMode",
    "Assigned",
    "AwaitingIntegration",
    "BlockReason",
    "Blocked",
    "Budget",
    "ChangeKind",
    "Channel",
    "ChannelState",
    "CheckOutcome",
    "CheckResult",
    "Claim",
    "ConflictReport",
    "ConflictSource",
    "ConflictedFile",
    "Contract",
    "ContractBreach",
    "Defer",
    "DenialReason",
    "Directive",
    "DriftStatus",
    "Envelope",
    "EscalateToForeman",
    "EventPayload",
    "Extract",
    "FileChange",
    "GateReport",
    "Landed",
    "Lease",
    "LeaseDecision",
    "LeaseDenied",
    "LeaseGranted",
    "LeaseQueued",
    "MergeOutcome",
    "MergeTreeResult",
    "Message",
    "ModuleNode",
    "NegotiationLimits",
    "NegotiationMove",
    "Note",
    "PathScope",
    "Pending",
    "RebaseOutcome",
    "RepoMap",
    "Resolution",
    "Ruling",
    "Running",
    "Scope",
    "Severity",
    "Snapshot",
    "Split",
    "StandConfig",
    "SymbolRef",
    "SymbolScope",
    "Task",
    "TaskGraph",
    "TaskSpec",
    "Topic",
    "WorkingStatus",
    "Workstream",
    "Worktree",
    "event_kinds",
    "modes_conflict",
    "scopes_overlap",
    "signature_digest",
]
